// Generated by gencpp from file phidgets_ik/SetDigitalOutputRequest.msg
// DO NOT EDIT!


#ifndef PHIDGETS_IK_MESSAGE_SETDIGITALOUTPUTREQUEST_H
#define PHIDGETS_IK_MESSAGE_SETDIGITALOUTPUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phidgets_ik
{
template <class ContainerAllocator>
struct SetDigitalOutputRequest_
{
  typedef SetDigitalOutputRequest_<ContainerAllocator> Type;

  SetDigitalOutputRequest_()
    : index(0)
    , state(false)  {
    }
  SetDigitalOutputRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , state(false)  {
  (void)_alloc;
    }



   typedef uint16_t _index_type;
  _index_type index;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDigitalOutputRequest_

typedef ::phidgets_ik::SetDigitalOutputRequest_<std::allocator<void> > SetDigitalOutputRequest;

typedef boost::shared_ptr< ::phidgets_ik::SetDigitalOutputRequest > SetDigitalOutputRequestPtr;
typedef boost::shared_ptr< ::phidgets_ik::SetDigitalOutputRequest const> SetDigitalOutputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidgets_ik

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87b461c46634beb857c7651b37066682";
  }

  static const char* value(const ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87b461c46634beb8ULL;
  static const uint64_t static_value2 = 0x57c7651b37066682ULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidgets_ik/SetDigitalOutputRequest";
  }

  static const char* value(const ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
uint16 index\n\
bool state\n\
";
  }

  static const char* value(const ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDigitalOutputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidgets_ik::SetDigitalOutputRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.index);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_IK_MESSAGE_SETDIGITALOUTPUTREQUEST_H
